- name: Build Docker image and start container Kubespray
  hosts: utils03
  gather_facts: false
  tasks:
    - name: pull image
      command: docker pull quay.io/kubespray/kubespray:v2.25.1

    - name: Stop the old container
      community.docker.docker_container:
        name: kubespray
        state: stopped
      ignore_errors: yes  # Ignore errors if the container is not running

    - name: Remove the old container
      community.docker.docker_container:
        name: kubespray
        state: absent
      ignore_errors: yes 

    - name: Remove the old Docker image
      community.docker.docker_image:
        name: kubespray:master
        state: absent   

    - name: Start Docker container
      docker_container:
        name: kubespray
        #image: kubespray:latest
        image: quay.io/kubespray/kubespray:v2.25.1
        state: started
        interactive: true
        tty: true
        volumes:
          - /root/inventory:/kubespray/inventory
