- name: Build Docker image and start container Kubespray
  hosts: utils03
  gather_facts: false
  tasks:
  #  - name: Clone Kubespray repository
  #    git:
  #      repo: https://github.com/kubernetes-sigs/kubespray.git
  #      dest: /root/kubespray  # Replace with the desired destination path
  
    - name: Stop the old container
      community.docker.docker_container:
        name: kubespray
        state: stopped
      ignore_errors: yes  # Ignore errors if the container is not running

    - name: Remove the old container
      community.docker.docker_container:
        name: kubespray
        state: absent
      ignore_errors: yes 

    - name: Remove the old Docker image
      community.docker.docker_image:
        name: kubespray:latest
        state: absent   

    - name: Build Docker image
      community.docker.docker_image:
        name: kubespray:latest
        build:
          path: /root/kubespray
        source: build
        force: yes 

    - name: Start Docker container
      docker_container:
        name: kubespray
        image: kubespray:latest
        #image: quay.io/kubespray/kubespray:v2.23.0
        state: started
        interactive: true
        tty: true
        volumes:
          - /root/inventory:/kubespray/inventory
