---
- name: Run Kubespray Playbook in Docker Container
  hosts: utils03
  tasks:
    - name: Run Ansible Playbook in Docker Container
      command: docker exec -it kubespray bash -c ' ansible-playbook -i /kubespray/inventory/discloud/inventory.ini /kubespray/cluster.yml -e kube_version=v1.28.5 -e calico_pool_blocksize=24  -e crio_packages=1.27'
      register: log

    - debug: msg="{{ log.stdout }}"  
