---
- name: Run Kubespray Playbook in Docker Container
  hosts: utils03
  tasks:
    - name: Pull Kubespray Docker Image
      docker_image:
        name: quay.io/kubespray/kubespray:v2.21.0

    - name: Start Kubespray Docker Container
      docker_container:
        name: kubespray
        image: quay.io/kubespray/kubespray:v2.21.0
        state: started
        interactive: true
        tty: true
        remove_on_exit: true
        volumes:
          - type: bind
            source: "/root/inventory/discloud"
            target: /inventory
          - type: bind
            source: "/root/inventory/ssh/id_rsa"
            target: /root/.ssh/id_rsa

    - name: Run Ansible Playbook in Docker Container
      command: docker exec -it kubespray bash -c 'nsible-playbook -i /inventory/inventory.ini --private-key /root/.ssh/id_rsa cluster.yml -e kube_version=v1.25.6 -e calico_pool_blocksize=24  -e crio_packages=1.24'
